# Generated by Django 4.0.4 on 2022-06-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completer',
            new_name='complete',
        ),
    ]
